const express = require('express');
const { readTable, isSameClinicDay, clinicDateKey, clinicShift, applyDateRange, applyStaffEntryLimit, staffLimitInfo } = require('../db');
const { authenticate } = require('../middleware/auth');
const router = express.Router();
router.use(authenticate);

router.get('/summary',(req,res)=>{const invoices=readTable('invoices');const isStaff=req.user.role==='staff';let{range,from,to}=req.query;if(isStaff){range='today';from=undefined;to=undefined}else if(!range&&!from&&!to)range='today';let scopedInvoices=applyDateRange(invoices,{range,from,to});let todaysInvoices=invoices.filter(i=>isSameClinicDay(i.createdAt));let staffLimit=null;if(isStaff){const settings=readTable('settings');const totalAvailable=scopedInvoices.length;scopedInvoices=applyStaffEntryLimit(scopedInvoices,settings);todaysInvoices=applyStaffEntryLimit(todaysInvoices,settings);staffLimit=staffLimitInfo(settings,totalAvailable,scopedInvoices.length)}res.json({range:isStaff?'today':range,totalSales:scopedInvoices.reduce((s,i)=>s+i.total,0),totalRevenue:scopedInvoices.reduce((s,i)=>s+i.amountPaid,0),testsPerformed:scopedInvoices.reduce((s,i)=>s+i.items.length,0),totalInvoices:scopedInvoices.length,todaysRevenue:todaysInvoices.reduce((s,i)=>s+i.amountPaid,0),todaysInvoicesCount:todaysInvoices.length,pendingDues:scopedInvoices.reduce((s,i)=>s+i.dueAmount,0),lockedToToday:isStaff,staffLimit})});
router.get('/revenue-trend',(req,res)=>{const isStaff=req.user.role==='staff';const days=isStaff?1:(Number(req.query.days)||14);const invoices=readTable('invoices');const result=[];for(let i=days-1;i>=0;i--){const date=new Date();date.setDate(date.getDate()-i);const key=clinicDateKey(date);const dayInvoices=invoices.filter(inv=>clinicDateKey(new Date(inv.createdAt))===key);result.push({date:key,revenue:dayInvoices.reduce((s,inv)=>s+inv.amountPaid,0),invoices:dayInvoices.length})}res.json(result)});
router.get('/test-distribution',(req,res)=>{const{range,from,to}=req.query;const invoices=applyDateRange(readTable('invoices'),{range,from,to});const counts={};invoices.forEach(invoice=>invoice.items.forEach(item=>{const name=item.description||'Unknown Test';counts[name]=(counts[name]||0)+(Number(item.quantity)||1)}));res.json(Object.entries(counts).map(([name,value])=>({name,value,count:value})).sort((a,b)=>b.value-a.value).slice(0,10))});
router.get('/daily-revenue',(req,res)=>{const{range,from,to}=req.query;const invoices=applyDateRange(readTable('invoices'),{range,from,to});const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];const totals=Object.fromEntries(days.map(d=>[d,0]));invoices.forEach(i=>{totals[days[new Date(i.createdAt).getDay()]]+=i.amountPaid||0});res.json(days.map(day=>({day,revenue:totals[day]||0})))});
router.get('/most-performed-tests',(req,res)=>{const counts={};readTable('invoices').forEach(inv=>inv.items.forEach(it=>{const key=it.description;if(!counts[key])counts[key]={name:key,count:0,revenue:0};counts[key].count+=it.quantity;counts[key].revenue+=it.amount}));res.json(Object.values(counts).sort((a,b)=>b.count-a.count).slice(0,15))});
router.get('/radiology-reports',(req,res)=>{const{shift}=req.query;const bookedBy=(req.query.bookedBy||'').toString().trim();const patient=(req.query.patient||'').toString().trim();const doctor=(req.query.doctor||'').toString().trim();let{from,to,range}=req.query;const isStaff=req.user.role==='staff';if(isStaff){range='today';from=undefined;to=undefined}else if(!from&&!to&&!range)range='today';let invoices=applyDateRange(readTable('invoices'),{range,from,to});if(shift==='Morning'||shift==='Evening')invoices=invoices.filter(i=>clinicShift(i.createdAt)===shift);const patients=readTable('patients');const patientMap=Object.fromEntries(patients.map(p=>[p.id,p]));const bookedByOptions=[...new Set(invoices.map(i=>(i.createdByName||'').toString().trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));if(bookedBy){const needle=bookedBy.toLowerCase();invoices=invoices.filter(i=>(i.createdByName||'').toString().trim().toLowerCase()===needle)}if(patient){const needle=patient.toLowerCase();invoices=invoices.filter(i=>{const name=(i.patientSnapshot?.name||patientMap[i.patientId]?.name||'').toString().toLowerCase();const mr=(i.patientSnapshot?.mrNumber||patientMap[i.patientId]?.mrNumber||'').toString().toLowerCase();return name.includes(needle)||mr.includes(needle)})}if(doctor){const needle=doctor.toLowerCase();invoices=invoices.filter(i=>(i.patientSnapshot?.doctorName||patientMap[i.patientId]?.doctorName||'').toString().toLowerCase().includes(needle))}let staffLimit=null;if(isStaff&&!bookedBy&&!patient&&!doctor){const settings=readTable('settings');const totalAvailable=invoices.length;invoices=applyStaffEntryLimit(invoices,settings);staffLimit=staffLimitInfo(settings,totalAvailable,invoices.length)}const sorted=invoices.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));const rows=sorted.map(i=>({invoiceNumber:i.invoiceNumber,mrNumber:i.patientSnapshot?.mrNumber,patientName:i.patientSnapshot?.name,referredBy:i.referralName||'',total:i.total,paid:i.amountPaid,discount:i.discountAmount,due:i.dueAmount,advance:i.advance,appointedDoctor:i.patientSnapshot?.doctorName||patientMap[i.patientId]?.doctorName||'',shift:clinicShift(i.createdAt),createdAt:i.createdAt,bookedBy:i.createdByName||'',updatedBy:i.updatedByName||''}));res.json({range,rows,bookedByOptions,limits:isStaff?{lockedToToday:true,staffLimit}:null})});
router.get('/pending-payments',(req,res)=>{const invoices=readTable('invoices').filter(i=>i.dueAmount>0);res.json(invoices.sort((a,b)=>b.dueAmount-a.dueAmount))});
module.exports=router;
