import React,{useEffect,useState}from'react';
import{Capacitor,registerPlugin}from'@capacitor/core';
import{Filter,Download,Printer,FileSpreadsheet,Search,TrendingUp}from'lucide-react';
import*as XLSX from'xlsx';
import Layout from'../components/Layout.jsx';import Button from'../components/Button.jsx';import TableLoadingRow from'../components/TableLoadingRow.jsx';import api from'../api/axios';import{useAuth}from'../context/AuthContext.jsx';
const NativePrint=registerPlugin('Print'),NativeExport=registerPlugin('Export');
const REPORT_HEADER=['Invoice#','MR#','Patient','Referred By','Total','Paid','Discount','Due','Doctor','Shift','Booked By','Date'];
const rowValues=r=>[r.invoiceNumber,r.mrNumber,r.patientName,r.referredBy,r.total,r.paid,r.discount,r.due,r.appointedDoctor,r.shift,r.bookedBy,r.createdAt];
const summaryValues=rows=>['','','','TOTAL',rows.reduce((s,r)=>s+Number(r.total||0),0),rows.reduce((s,r)=>s+Number(r.paid||0),0),rows.reduce((s,r)=>s+Number(r.discount||0),0),'','','','',''];
const b64=bytes=>{let x='';for(let i=0;i<bytes.length;i+=0x8000)x+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(x)};
const text64=t=>b64(new TextEncoder().encode(t));
function reportHtml(rows){const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const head=REPORT_HEADER.map(h=>`<th>${esc(h)}</th>`).join('');const body=rows.map(r=>`<tr>${rowValues(r).map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('');const total=rows.length?`<tfoot><tr>${summaryValues(rows).map(v=>`<td>${esc(v)}</td>`).join('')}</tr></tfoot>`:'';return`<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;padding:0;background:#fff;font-family:Arial,sans-serif;color:#111}h1{font-size:18px;margin:0 0 12px}table{width:100%;border-collapse:collapse;font-size:9px}th,td{border:1px solid #bbb;padding:5px;text-align:left}th{background:#eee;font-weight:700}tfoot td{font-weight:700;background:#f5f5f5}@page{size:A4 landscape;margin:8mm}</style></head><body><h1>Radiology Reports</h1><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody>${total}</table></body></html>`}
export default function RadiologyReports(){
 const{isAdmin}=useAuth();const[rows,setRows]=useState([]),[limits,setLimits]=useState(null),[bookedByOptions,setBookedByOptions]=useState([]),[range,setRange]=useState('today'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[shift,setShift]=useState(''),[bookedBy,setBookedBy]=useState(''),[patient,setPatient]=useState(''),[doctor,setDoctor]=useState(''),[loading,setLoading]=useState(true),[exporting,setExporting]=useState('');
 const load=(opts={})=>{const r=opts.range??range,f=opts.from??from,t=opts.to??to,s=opts.shift??shift,b=opts.bookedBy??bookedBy,p=opts.patient??patient,d=opts.doctor??doctor;setLoading(true);api.get('/reports/radiology-reports',{params:{range:f||t?undefined:r,from:f||undefined,to:t||undefined,shift:s||undefined,bookedBy:b||undefined,patient:p.trim()||undefined,doctor:d.trim()||undefined}}).then(res=>{setRows(res.data.rows||[]);setLimits(res.data.limits);setBookedByOptions(res.data.bookedByOptions||[]);if(res.data.range&&res.data.range!==r)setRange(res.data.range)}).catch(e=>console.error('Radiology report load failed',e)).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[]);
 const selectRange=k=>{setRange(k);setFrom('');setTo('');load({range:k,from:'',to:''})};const applyDate=()=>load({from,to});const selectShift=k=>{const n=shift===k?'':k;setShift(n);load({shift:n})};const clearFilters=()=>{setBookedBy('');setPatient('');setDoctor('');load({bookedBy:'',patient:'',doctor:''})};
 const totalRevenue=rows.reduce((s,r)=>s+Number(r.paid||0),0);
 const exportCsv=async()=>{if(exporting)return;setExporting('csv');try{const lines=rows.map(r=>rowValues(r).map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(','));const csv=[REPORT_HEADER.join(','),...lines,...(rows.length?[summaryValues(rows).map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')]:[])].join('\r\n');if(Capacitor.isNativePlatform()&&Capacitor.getPlatform()==='android')await NativeExport.save({name:'radiology-reports.csv',mime:'text/csv',data:text64('\uFEFF'+csv)});else{const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='radiology-reports.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}}catch(e){alert(e?.message||'CSV export failed.')}finally{setExporting('')}};
 const exportXlsx=async()=>{if(exporting)return;setExporting('xlsx');try{const sheet=XLSX.utils.aoa_to_sheet([REPORT_HEADER,...rows.map(rowValues),...(rows.length?[summaryValues(rows)]:[])]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,sheet,'Radiology Reports');if(Capacitor.isNativePlatform()&&Capacitor.getPlatform()==='android')await NativeExport.save({name:'radiology-reports.xlsx',mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',data:XLSX.write(wb,{bookType:'xlsx',type:'base64'})});else XLSX.writeFile(wb,'radiology-reports.xlsx')}catch(e){alert(e?.message||'Excel export failed.')}finally{setExporting('')}};
 const print=async()=>{try{if(Capacitor.isNativePlatform()&&Capacitor.getPlatform()==='android')await NativePrint.print({html:reportHtml(rows),name:'Rizvi Diagnostic Reports'});else window.print()}catch(e){alert(e?.message||'Printing failed.')}};
 return <Layout title="Radiology Reports">
  {isAdmin&&<div className="flex flex-wrap items-center gap-2 mb-4">{[['today','Today'],['yesterday','Yesterday'],['last3','Last 3 Days'],['all','All / Date Range']].map(([k,l])=><button key={k} onClick={()=>selectRange(k)} className={`px-3 sm:px-4 py-2 rounded-lg text-xs sm:text-sm font-medium ${range===k&&!from&&!to?'bg-brand-600 text-white':'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'}`}>{l}</button>)}</div>}
  <div className="flex flex-wrap items-center gap-2 mb-4"><span className="text-xs font-medium text-slate-500 mr-1">Shift:</span>{['Morning','Evening'].map(k=><button key={k} onClick={()=>selectShift(k)} className={`px-3 sm:px-4 py-2 rounded-lg text-xs sm:text-sm font-medium ${shift===k?'bg-brand-600 text-white':'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'}`}>{k} Shift</button>)}</div>
  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3 mb-4 bg-white rounded-xl border border-slate-100 shadow-sm p-4">
   {isAdmin&&<><div><label className="block text-xs font-medium text-slate-500 mb-1">From</label><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm"/></div><div><label className="block text-xs font-medium text-slate-500 mb-1">To</label><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm"/></div><div className="flex items-end"><Button onClick={applyDate} icon={Filter}>Filter by Date</Button></div></>}
   <div><label className="block text-xs font-medium text-slate-500 mb-1">Booked By</label><select value={bookedBy} onChange={e=>{setBookedBy(e.target.value);load({bookedBy:e.target.value})}} className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm bg-white"><option value="">All Booked By</option>{bookedByOptions.map(name=><option key={name} value={name}>{name}</option>)}</select></div>
   <div><label className="block text-xs font-medium text-slate-500 mb-1">Patient</label><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={patient} onChange={e=>setPatient(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load({patient:e.target.value})}} placeholder="Search patient / MR#" className="w-full border border-slate-200 rounded-lg pl-9 pr-3 py-2 text-sm"/></div></div>
   <div><label className="block text-xs font-medium text-slate-500 mb-1">Doctor</label><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={doctor} onChange={e=>setDoctor(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load({doctor:e.target.value})}} placeholder="Search doctor" className="w-full border border-slate-200 rounded-lg pl-9 pr-3 py-2 text-sm"/></div></div>
   <div className="flex items-end gap-2"><Button onClick={()=>load({patient,doctor,bookedBy})} icon={Search} size="sm">Search</Button>{(bookedBy||patient||doctor)&&<button onClick={clearFilters} className="px-3 py-2 rounded-lg text-sm text-slate-500 border border-slate-200 hover:bg-slate-50">Clear</button>}</div>
  </div>
  <div className="flex flex-col lg:flex-column reverse gap-3 mb-5"><div className="flex flex-wrap gap-2"><Button variant="secondary" icon={Download} onClick={exportCsv} disabled={!!exporting} size="sm">{exporting==='csv'?'Exporting…':'Export CSV'}</Button><Button variant="secondary" icon={FileSpreadsheet} onClick={exportXlsx} disabled={!!exporting} size="sm">{exporting==='xlsx'?'Exporting…':'Export Excel (.xlsx)'}</Button><Button variant="secondary" icon={Printer} onClick={print} disabled={!!exporting} size="sm">Print</Button></div><div className="lg:ml-auto w-full lg:w-[360px] rounded-2xl border border-emerald-100 bg-gradient-to-br from-emerald-50 via-white to-slate-50 px-5 py-4 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Total Revenue</p><p className="mt-1 text-2xl sm:text-3xl font-bold tracking-tight text-slate-900">Rs. {totalRevenue.toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">Collected from {rows.length.toLocaleString()} {rows.length===1?'entry':'entries'}</p></div><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700"><TrendingUp size={21}/></div></div></div></div>
  <div className="bg-white rounded-xl border border-slate-100 shadow-sm overflow-x-auto"><table className="w-full text-sm min-w-[980px]"><thead className="bg-slate-50 text-slate-500 text-left"><tr>{REPORT_HEADER.map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{loading?<TableLoadingRow colSpan={12}/>:!rows.length?<tr><td colSpan={12} className="p-6 text-center text-slate-400">There is no radiology report to show.</td></tr>:rows.map(r=><tr key={r.invoiceNumber} className="border-t border-slate-50 hover:bg-slate-50/60"><td className="p-3 font-mono text-xs">{r.invoiceNumber}</td><td className="p-3 font-mono text-xs">{r.mrNumber}</td><td className="p-3">{r.patientName}</td><td className="p-3">{r.referredBy||'-'}</td><td className="p-3">Rs. {Number(r.total||0).toLocaleString()}</td><td className="p-3 font-semibold text-emerald-700">Rs. {Number(r.paid||0).toLocaleString()}</td><td className="p-3">Rs. {Number(r.discount||0).toLocaleString()}</td><td className="p-3 text-red-600">Rs. {Number(r.due||0).toLocaleString()}</td><td className="p-3">{r.appointedDoctor||'-'}</td><td className="p-3">{r.shift||'-'}</td><td className="p-3 font-medium">{r.bookedBy||'-'}</td><td className="p-3">{new Date(r.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>
 </Layout>;
}
